ROOT = ../../
BINS = tutorial.exe tutorialgrad.exe tutorialbnb.exe tutorialbnbmt.exe
TESTS = tutorial.exe tutorialgrad.exe tutorialbnb.exe tutorialbnbmt.exe


include $(ROOT)all.inc
-include deps.inc
